Project Pull Request
mohametalmeari/Hello-Microverse pull request #1
Opened 2023-03-21 13:30 UTC by mohametalmeari

Create HTML file with "Hello Microverse!" message.
Create CSS file to style the HTML file.
Setup Linter

2023-03-21 14:11 UTC, franclobo reviewed
Hi @mohametalmeari, 

![terminator](https://user-images.githubusercontent.com/58642949/226632928-e1979a74-adb4-464a-957e-365a163f598b.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-21 19:16 UTC, mohametalmeari commented
> Hi @mohametalmeari,
> 
> ![terminator](https://user-images.githubusercontent.com/58642949/226632928-e1979a74-adb4-464a-957e-365a163f598b.gif) [ ![terminator](https://user-images.githubusercontent.com/58642949/226632928-e1979a74-adb4-464a-957e-365a163f598b.gif) ](https://user-images.githubusercontent.com/58642949/226632928-e1979a74-adb4-464a-957e-365a163f598b.gif) [ ](https://user-images.githubusercontent.com/58642949/226632928-e1979a74-adb4-464a-957e-365a163f598b.gif)
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has linter errors ❌
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._
Thank you for your review, unfortunately I couldn't solve the problem, I checked on Youtube but still can't fix it.

2023-03-22 07:53 UTC, AlphaNtihinduka requested changes
## Hi @mohametalmeari 🙋‍♂️
Good job working on your Hello Microverse project. You have done the design to the best expectation and incredibly well. 👏  

You still need to implement few on the project but you are almost there!!! 🚶 : 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

# Required Changes :recycle: 
You have submitted a project with a readme file that is not detailed. Kindly edit and customize your readme with the project information for it to be professional. You can consider using the [Microverse Readme template](https://github.com/microverseinc/readme-template) as the [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md#requirements) ☺️.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-03-22 14:30 UTC, mohametalmeari commented
Hi @franclobo, I fixed the error and customized the readme file.
Could you check the project before I submit it.
Thank you.

2023-03-24 08:08 UTC, topeogunleye requested changes
Hi @<STUDENT_MENTION>, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] As suggested by the previous reviewer, In the case of README, Kindly edit and customize your readme with the project information for it to be professional. consider not leaving any of the sections in the [Microverse README](https://github.com/microverseinc/readme-template) template as it's a project requirement.
- [ ] I kindly suggest that you add the table of contents from the README file.

| Text  | Images |
| ------------- | ------------- |
| Your README file| <img width="960" alt="image" src="https://user-images.githubusercontent.com/52934128/227461119-31653b60-d656-4572-a4bf-55b01b283a27.png"> |
| Professional README file | ![Recording 2023-02-14 at 12 52 20 (5)](https://user-images.githubusercontent.com/83360636/218715072-2b2d3a49-8219-4939-b350-45cc950f7f7a.gif) |

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 10:49 UTC, mohametalmeari commented
Hi @topeogunleye, I did the changes you mentioned, could check before I submit please.
Best Regards,

2023-03-24 11:29 UTC, aamirkhan2478 requested changes
Hi @mohametalmeari , 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

[OPTIONAL] Kindly resolve your conflict in your project by watching this [video](https://www.youtube.com/watch?v=mOJazBNrG-c)

[OPTIONAL] Kindly use a descriptive `branch` name your branch name should be any feature or action like `add-heading` this requirement is optional but recommended next time whenever you create a new branch kindly create a descriptive and meaningful branch name. :+1: 

[OPTIONAL] Your `PR title` and `PR summary` are not descriptive and meaningful kindly add descriptive and meaningful `PR title` and `PR summary`. Check below :point_down: example of descriptive and meaningful `title` and `summary`. :slightly_smiling_face: 

![219520522-f0a8c7ba-b272-4a26-81c7-c233913f9c1e](https://user-images.githubusercontent.com/45226848/227507678-ecc15372-4060-48e6-985f-8187c88648b0.png)
 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 11:29 UTC, aamirkhan2478 commented on README.md
> +</details>
- [ ] Please remove the `Server` and `Database` details because you are not using any server and database in this project so kindly remove them. Also, add `HTML` and `CSS` in the `Client` details. Check below :point_down: my suggestions :slightly_smiling_face: 

```suggestion
<details>
  <summary>Client</summary>
  <ul>
    <li><a href="https://www.w3schools.com/html/">HTML</a></li>
    <li><a href="https://www.w3schools.com/css/">CSS</a></li>
  </ul>
</details>
```

2023-03-24 11:29 UTC, aamirkhan2478 commented on README.md
> +  gem install
- [ ] Kindly replace `gem` with `npm` because you are not using any gem in this project so kindly replace it.

2023-03-24 11:29 UTC, aamirkhan2478 commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Kindly fix your `MIT` link its not working check my suggestion below :point_down: 

```suggestion
This project is [MIT](./MIT.md) licensed.
```

2023-03-24 11:29 UTC, aamirkhan2478 commented on README.md
> +  rails server
- [ ] Please remove the `rails server` from here because you are not using rails in this project so remove it and add `how to open your project in the browser?` like `Double click on HTML file and the HTML file will be open in your browser.` so kindly replace it. :slightly_smiling_face:

2023-03-24 11:29 UTC, aamirkhan2478 commented on README.md
> +  bin/rails test test/models/article_test.rb
- [ ] Please remove this command from here because you are not using rails and also not performing any test in this project so kindly remove it.

2023-03-24 13:30 UTC, mohametalmeari commented on README.md
> +  bin/rails test test/models/article_test.rb
Hi @aamirkhan2478, could you check the changes before I request an extra review, because I used all 3 review requests for this project.

2023-03-24 13:30 UTC, mohametalmeari commented
Hi @aamirkhan2478, could you check the changes before I request an extra review, because I used all 3 review requests for this project.

2023-03-24 14:07 UTC, aamirkhan2478 commented
> Hi @aamirkhan2478, could you check the changes before I request an extra review, because I used all 3 review requests for this project.

Yeah, now it's okay :+1:

2023-03-24 14:40 UTC, topeogunleye commented
> Hi @topeogunleye, I did the changes you mentioned, could check before I submit please. Best Regards,

@mohametalmeari. Sorry for the late respinse. Congratulations on your Approval 👍

2023-03-24 15:48 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct . :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions
- [OPTIONAL] Kindly ensure you give your PR a descriptive some other time to avoid PR invalidation. Your present pr title is not descriptve. Something like `Hello Microverse` would have been better.

![pr-title](https://user-images.githubusercontent.com/26597432/227574637-2822fd6f-4e89-4db0-855c-a10ef4e6ddaa.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 15:56 UTC, merged